name: send-anywhere

services:
  send-anywhere:
    build:
      context: ./repo
      dockerfile: Dockerfile
    container_name: send-anywhere
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /opt/stack/data/send-anywhere/uploads:/data/uploads
      - /opt/stack/data/send-anywhere/db:/data/db
    networks:
      - edge_shared

networks:
  edge_shared:
    external: true
